name: Django CI

on:
  workflow_dispatch:         #  Have to manually run the pipeline
  
jobs:
  build:

    runs-on: windows-latest                # Installing an image 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.8                        # Setting up the python environment 
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies                      # Installing the Requriements 
      run: |
        python -m pip install --upgrade pip               
        pip install -r requirements.txt 
        pwd
        ls

    - name: Run tests
      run: |
        python manage.py test

    
